# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.collect_status_response import CollectStatusResponse
from .raw_client import AsyncRawOpenTelemetryClient, RawOpenTelemetryClient


class OpenTelemetryClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOpenTelemetryClient(client_wrapper=client_wrapper)
    
    @property
    def with_raw_response(self) -> RawOpenTelemetryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.
        
        Returns
        -------
        RawOpenTelemetryClient
        """
        return self._raw_client
    
    def otlp_status(self, *, request_options: typing.Optional[RequestOptions] = None) -> CollectStatusResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        CollectStatusResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.open_telemetry.otlp_status()
        """
        _response = self._raw_client.otlp_status(request_options=request_options)
        return _response.data
    
    def otlp_ingest(self, *, request_options: typing.Optional[RequestOptions] = None) -> CollectStatusResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        CollectStatusResponse
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.open_telemetry.otlp_ingest()
        """
        _response = self._raw_client.otlp_ingest(request_options=request_options)
        return _response.data
class AsyncOpenTelemetryClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOpenTelemetryClient(client_wrapper=client_wrapper)
    
    @property
    def with_raw_response(self) -> AsyncRawOpenTelemetryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.
        
        Returns
        -------
        AsyncRawOpenTelemetryClient
        """
        return self._raw_client
    
    async def otlp_status(self, *, request_options: typing.Optional[RequestOptions] = None) -> CollectStatusResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        CollectStatusResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.open_telemetry.otlp_status()
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.otlp_status(request_options=request_options)
        return _response.data
    
    async def otlp_ingest(self, *, request_options: typing.Optional[RequestOptions] = None) -> CollectStatusResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        CollectStatusResponse
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.open_telemetry.otlp_ingest()
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.otlp_ingest(request_options=request_options)
        return _response.data
