# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.config_response_model import ConfigResponseModel
from ..types.reference_request_model_input import ReferenceRequestModelInput
from .raw_client import AsyncRawDeprecatedClient, RawDeprecatedClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)
class DeprecatedClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDeprecatedClient(client_wrapper=client_wrapper)
    
    @property
    def with_raw_response(self) -> RawDeprecatedClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.
        
        Returns
        -------
        RawDeprecatedClient
        """
        return self._raw_client
    
    def configs_fetch(self, *, variant_ref: typing.Optional[ReferenceRequestModelInput] = OMIT, environment_ref: typing.Optional[ReferenceRequestModelInput] = OMIT, application_ref: typing.Optional[ReferenceRequestModelInput] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> ConfigResponseModel:
        """
        Parameters
        ----------
        variant_ref : typing.Optional[ReferenceRequestModelInput]
        
        environment_ref : typing.Optional[ReferenceRequestModelInput]
        
        application_ref : typing.Optional[ReferenceRequestModelInput]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        ConfigResponseModel
            Successful Response
        
        Examples
        --------
        from agenta import AgentaApi
        
        client = AgentaApi(
            api_key="YOUR_API_KEY",
        )
        client.deprecated.configs_fetch()
        """
        _response = self._raw_client.configs_fetch(variant_ref=variant_ref, environment_ref=environment_ref, application_ref=application_ref, request_options=request_options)
        return _response.data
class AsyncDeprecatedClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDeprecatedClient(client_wrapper=client_wrapper)
    
    @property
    def with_raw_response(self) -> AsyncRawDeprecatedClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.
        
        Returns
        -------
        AsyncRawDeprecatedClient
        """
        return self._raw_client
    
    async def configs_fetch(self, *, variant_ref: typing.Optional[ReferenceRequestModelInput] = OMIT, environment_ref: typing.Optional[ReferenceRequestModelInput] = OMIT, application_ref: typing.Optional[ReferenceRequestModelInput] = OMIT, request_options: typing.Optional[RequestOptions] = None) -> ConfigResponseModel:
        """
        Parameters
        ----------
        variant_ref : typing.Optional[ReferenceRequestModelInput]
        
        environment_ref : typing.Optional[ReferenceRequestModelInput]
        
        application_ref : typing.Optional[ReferenceRequestModelInput]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        ConfigResponseModel
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from agenta import AsyncAgentaApi
        
        client = AsyncAgentaApi(
            api_key="YOUR_API_KEY",
        )
        
        
        async def main() -> None:
            await client.deprecated.configs_fetch()
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.configs_fetch(variant_ref=variant_ref, environment_ref=environment_ref, application_ref=application_ref, request_options=request_options)
        return _response.data
