# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .environment import AgentaApiEnvironment

if typing.TYPE_CHECKING:
    from .admin.client import AdminClient, AsyncAdminClient
    from .applications.client import ApplicationsClient, AsyncApplicationsClient
    from .billing.client import AsyncBillingClient, BillingClient
    from .deprecated.client import AsyncDeprecatedClient, DeprecatedClient
    from .environments.client import AsyncEnvironmentsClient, EnvironmentsClient
    from .evaluations.client import AsyncEvaluationsClient, EvaluationsClient
    from .evaluators.client import AsyncEvaluatorsClient, EvaluatorsClient
    from .events.client import AsyncEventsClient, EventsClient
    from .folders.client import AsyncFoldersClient, FoldersClient
    from .keys.client import AsyncKeysClient, KeysClient
    from .open_telemetry.client import AsyncOpenTelemetryClient, OpenTelemetryClient
    from .organizations.client import AsyncOrganizationsClient, OrganizationsClient
    from .projects.client import AsyncProjectsClient, ProjectsClient
    from .queries.client import AsyncQueriesClient, QueriesClient
    from .secrets.client import AsyncSecretsClient, SecretsClient
    from .status.client import AsyncStatusClient, StatusClient
    from .testcases.client import AsyncTestcasesClient, TestcasesClient
    from .testsets.client import AsyncTestsetsClient, TestsetsClient
    from .tools.client import AsyncToolsClient, ToolsClient
    from .traces.client import AsyncTracesClient, TracesClient
    from .users.client import AsyncUsersClient, UsersClient
    from .webhooks.client import AsyncWebhooksClient, WebhooksClient
    from .workflows.client import AsyncWorkflowsClient, WorkflowsClient
    from .workspaces.client import AsyncWorkspacesClient, WorkspacesClient
class AgentaApi:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.
    
    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.
    
    environment : AgentaApiEnvironment
        The environment to use for requests from the client. from .environment import AgentaApiEnvironment
        
        
        
        Defaults to AgentaApiEnvironment.DEFAULT
        
        
    
    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.
    
    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.
    
    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.
    
    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.
    
    Examples
    --------
    from agenta import AgentaApi
    
    client = AgentaApi(
        api_key="YOUR_API_KEY",
    )
    """
    def __init__(self, *, base_url: typing.Optional[str] = None, environment: AgentaApiEnvironment = AgentaApiEnvironment.DEFAULT
    , api_key: str, headers: typing.Optional[typing.Dict[str, str]] = None, timeout: typing.Optional[float] = None, follow_redirects: typing.Optional[bool] = True, httpx_client: typing.Optional[httpx.Client] = None):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        self._client_wrapper = SyncClientWrapper(base_url=_get_base_url(base_url=base_url, environment=environment), api_key=api_key, headers=headers, httpx_client=httpx_client if httpx_client is not None else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects) if follow_redirects is not None else httpx.Client(timeout=_defaulted_timeout)
        , timeout=_defaulted_timeout)
        self._billing: typing.Optional[BillingClient] = None
        self._admin: typing.Optional[AdminClient] = None
        self._organizations: typing.Optional[OrganizationsClient] = None
        self._workspaces: typing.Optional[WorkspacesClient] = None
        self._secrets: typing.Optional[SecretsClient] = None
        self._webhooks: typing.Optional[WebhooksClient] = None
        self._open_telemetry: typing.Optional[OpenTelemetryClient] = None
        self._traces: typing.Optional[TracesClient] = None
        self._events: typing.Optional[EventsClient] = None
        self._testcases: typing.Optional[TestcasesClient] = None
        self._testsets: typing.Optional[TestsetsClient] = None
        self._queries: typing.Optional[QueriesClient] = None
        self._folders: typing.Optional[FoldersClient] = None
        self._applications: typing.Optional[ApplicationsClient] = None
        self._workflows: typing.Optional[WorkflowsClient] = None
        self._evaluators: typing.Optional[EvaluatorsClient] = None
        self._environments: typing.Optional[EnvironmentsClient] = None
        self._deprecated: typing.Optional[DeprecatedClient] = None
        self._tools: typing.Optional[ToolsClient] = None
        self._evaluations: typing.Optional[EvaluationsClient] = None
        self._status: typing.Optional[StatusClient] = None
        self._projects: typing.Optional[ProjectsClient] = None
        self._users: typing.Optional[UsersClient] = None
        self._keys: typing.Optional[KeysClient] = None
    
    @property
    def billing(self):
        if self._billing is None:
            from .billing.client import BillingClient  # noqa: E402
            self._billing = BillingClient(client_wrapper=self._client_wrapper)
        return self._billing
    
    @property
    def admin(self):
        if self._admin is None:
            from .admin.client import AdminClient  # noqa: E402
            self._admin = AdminClient(client_wrapper=self._client_wrapper)
        return self._admin
    
    @property
    def organizations(self):
        if self._organizations is None:
            from .organizations.client import OrganizationsClient  # noqa: E402
            self._organizations = OrganizationsClient(client_wrapper=self._client_wrapper)
        return self._organizations
    
    @property
    def workspaces(self):
        if self._workspaces is None:
            from .workspaces.client import WorkspacesClient  # noqa: E402
            self._workspaces = WorkspacesClient(client_wrapper=self._client_wrapper)
        return self._workspaces
    
    @property
    def secrets(self):
        if self._secrets is None:
            from .secrets.client import SecretsClient  # noqa: E402
            self._secrets = SecretsClient(client_wrapper=self._client_wrapper)
        return self._secrets
    
    @property
    def webhooks(self):
        if self._webhooks is None:
            from .webhooks.client import WebhooksClient  # noqa: E402
            self._webhooks = WebhooksClient(client_wrapper=self._client_wrapper)
        return self._webhooks
    
    @property
    def open_telemetry(self):
        if self._open_telemetry is None:
            from .open_telemetry.client import OpenTelemetryClient  # noqa: E402
            self._open_telemetry = OpenTelemetryClient(client_wrapper=self._client_wrapper)
        return self._open_telemetry
    
    @property
    def traces(self):
        if self._traces is None:
            from .traces.client import TracesClient  # noqa: E402
            self._traces = TracesClient(client_wrapper=self._client_wrapper)
        return self._traces
    
    @property
    def events(self):
        if self._events is None:
            from .events.client import EventsClient  # noqa: E402
            self._events = EventsClient(client_wrapper=self._client_wrapper)
        return self._events
    
    @property
    def testcases(self):
        if self._testcases is None:
            from .testcases.client import TestcasesClient  # noqa: E402
            self._testcases = TestcasesClient(client_wrapper=self._client_wrapper)
        return self._testcases
    
    @property
    def testsets(self):
        if self._testsets is None:
            from .testsets.client import TestsetsClient  # noqa: E402
            self._testsets = TestsetsClient(client_wrapper=self._client_wrapper)
        return self._testsets
    
    @property
    def queries(self):
        if self._queries is None:
            from .queries.client import QueriesClient  # noqa: E402
            self._queries = QueriesClient(client_wrapper=self._client_wrapper)
        return self._queries
    
    @property
    def folders(self):
        if self._folders is None:
            from .folders.client import FoldersClient  # noqa: E402
            self._folders = FoldersClient(client_wrapper=self._client_wrapper)
        return self._folders
    
    @property
    def applications(self):
        if self._applications is None:
            from .applications.client import ApplicationsClient  # noqa: E402
            self._applications = ApplicationsClient(client_wrapper=self._client_wrapper)
        return self._applications
    
    @property
    def workflows(self):
        if self._workflows is None:
            from .workflows.client import WorkflowsClient  # noqa: E402
            self._workflows = WorkflowsClient(client_wrapper=self._client_wrapper)
        return self._workflows
    
    @property
    def evaluators(self):
        if self._evaluators is None:
            from .evaluators.client import EvaluatorsClient  # noqa: E402
            self._evaluators = EvaluatorsClient(client_wrapper=self._client_wrapper)
        return self._evaluators
    
    @property
    def environments(self):
        if self._environments is None:
            from .environments.client import EnvironmentsClient  # noqa: E402
            self._environments = EnvironmentsClient(client_wrapper=self._client_wrapper)
        return self._environments
    
    @property
    def deprecated(self):
        if self._deprecated is None:
            from .deprecated.client import DeprecatedClient  # noqa: E402
            self._deprecated = DeprecatedClient(client_wrapper=self._client_wrapper)
        return self._deprecated
    
    @property
    def tools(self):
        if self._tools is None:
            from .tools.client import ToolsClient  # noqa: E402
            self._tools = ToolsClient(client_wrapper=self._client_wrapper)
        return self._tools
    
    @property
    def evaluations(self):
        if self._evaluations is None:
            from .evaluations.client import EvaluationsClient  # noqa: E402
            self._evaluations = EvaluationsClient(client_wrapper=self._client_wrapper)
        return self._evaluations
    
    @property
    def status(self):
        if self._status is None:
            from .status.client import StatusClient  # noqa: E402
            self._status = StatusClient(client_wrapper=self._client_wrapper)
        return self._status
    
    @property
    def projects(self):
        if self._projects is None:
            from .projects.client import ProjectsClient  # noqa: E402
            self._projects = ProjectsClient(client_wrapper=self._client_wrapper)
        return self._projects
    
    @property
    def users(self):
        if self._users is None:
            from .users.client import UsersClient  # noqa: E402
            self._users = UsersClient(client_wrapper=self._client_wrapper)
        return self._users
    
    @property
    def keys(self):
        if self._keys is None:
            from .keys.client import KeysClient  # noqa: E402
            self._keys = KeysClient(client_wrapper=self._client_wrapper)
        return self._keys
class AsyncAgentaApi:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.
    
    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.
    
    environment : AgentaApiEnvironment
        The environment to use for requests from the client. from .environment import AgentaApiEnvironment
        
        
        
        Defaults to AgentaApiEnvironment.DEFAULT
        
        
    
    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.
    
    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.
    
    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.
    
    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.
    
    Examples
    --------
    from agenta import AsyncAgentaApi
    
    client = AsyncAgentaApi(
        api_key="YOUR_API_KEY",
    )
    """
    def __init__(self, *, base_url: typing.Optional[str] = None, environment: AgentaApiEnvironment = AgentaApiEnvironment.DEFAULT
    , api_key: str, headers: typing.Optional[typing.Dict[str, str]] = None, timeout: typing.Optional[float] = None, follow_redirects: typing.Optional[bool] = True, httpx_client: typing.Optional[httpx.AsyncClient] = None):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        self._client_wrapper = AsyncClientWrapper(base_url=_get_base_url(base_url=base_url, environment=environment), api_key=api_key, headers=headers, httpx_client=httpx_client if httpx_client is not None else httpx.AsyncClient(timeout=_defaulted_timeout, follow_redirects=follow_redirects) if follow_redirects is not None else httpx.AsyncClient(timeout=_defaulted_timeout)
        , timeout=_defaulted_timeout)
        self._billing: typing.Optional[AsyncBillingClient] = None
        self._admin: typing.Optional[AsyncAdminClient] = None
        self._organizations: typing.Optional[AsyncOrganizationsClient] = None
        self._workspaces: typing.Optional[AsyncWorkspacesClient] = None
        self._secrets: typing.Optional[AsyncSecretsClient] = None
        self._webhooks: typing.Optional[AsyncWebhooksClient] = None
        self._open_telemetry: typing.Optional[AsyncOpenTelemetryClient] = None
        self._traces: typing.Optional[AsyncTracesClient] = None
        self._events: typing.Optional[AsyncEventsClient] = None
        self._testcases: typing.Optional[AsyncTestcasesClient] = None
        self._testsets: typing.Optional[AsyncTestsetsClient] = None
        self._queries: typing.Optional[AsyncQueriesClient] = None
        self._folders: typing.Optional[AsyncFoldersClient] = None
        self._applications: typing.Optional[AsyncApplicationsClient] = None
        self._workflows: typing.Optional[AsyncWorkflowsClient] = None
        self._evaluators: typing.Optional[AsyncEvaluatorsClient] = None
        self._environments: typing.Optional[AsyncEnvironmentsClient] = None
        self._deprecated: typing.Optional[AsyncDeprecatedClient] = None
        self._tools: typing.Optional[AsyncToolsClient] = None
        self._evaluations: typing.Optional[AsyncEvaluationsClient] = None
        self._status: typing.Optional[AsyncStatusClient] = None
        self._projects: typing.Optional[AsyncProjectsClient] = None
        self._users: typing.Optional[AsyncUsersClient] = None
        self._keys: typing.Optional[AsyncKeysClient] = None
    
    @property
    def billing(self):
        if self._billing is None:
            from .billing.client import AsyncBillingClient  # noqa: E402
            self._billing = AsyncBillingClient(client_wrapper=self._client_wrapper)
        return self._billing
    
    @property
    def admin(self):
        if self._admin is None:
            from .admin.client import AsyncAdminClient  # noqa: E402
            self._admin = AsyncAdminClient(client_wrapper=self._client_wrapper)
        return self._admin
    
    @property
    def organizations(self):
        if self._organizations is None:
            from .organizations.client import AsyncOrganizationsClient  # noqa: E402
            self._organizations = AsyncOrganizationsClient(client_wrapper=self._client_wrapper)
        return self._organizations
    
    @property
    def workspaces(self):
        if self._workspaces is None:
            from .workspaces.client import AsyncWorkspacesClient  # noqa: E402
            self._workspaces = AsyncWorkspacesClient(client_wrapper=self._client_wrapper)
        return self._workspaces
    
    @property
    def secrets(self):
        if self._secrets is None:
            from .secrets.client import AsyncSecretsClient  # noqa: E402
            self._secrets = AsyncSecretsClient(client_wrapper=self._client_wrapper)
        return self._secrets
    
    @property
    def webhooks(self):
        if self._webhooks is None:
            from .webhooks.client import AsyncWebhooksClient  # noqa: E402
            self._webhooks = AsyncWebhooksClient(client_wrapper=self._client_wrapper)
        return self._webhooks
    
    @property
    def open_telemetry(self):
        if self._open_telemetry is None:
            from .open_telemetry.client import AsyncOpenTelemetryClient  # noqa: E402
            self._open_telemetry = AsyncOpenTelemetryClient(client_wrapper=self._client_wrapper)
        return self._open_telemetry
    
    @property
    def traces(self):
        if self._traces is None:
            from .traces.client import AsyncTracesClient  # noqa: E402
            self._traces = AsyncTracesClient(client_wrapper=self._client_wrapper)
        return self._traces
    
    @property
    def events(self):
        if self._events is None:
            from .events.client import AsyncEventsClient  # noqa: E402
            self._events = AsyncEventsClient(client_wrapper=self._client_wrapper)
        return self._events
    
    @property
    def testcases(self):
        if self._testcases is None:
            from .testcases.client import AsyncTestcasesClient  # noqa: E402
            self._testcases = AsyncTestcasesClient(client_wrapper=self._client_wrapper)
        return self._testcases
    
    @property
    def testsets(self):
        if self._testsets is None:
            from .testsets.client import AsyncTestsetsClient  # noqa: E402
            self._testsets = AsyncTestsetsClient(client_wrapper=self._client_wrapper)
        return self._testsets
    
    @property
    def queries(self):
        if self._queries is None:
            from .queries.client import AsyncQueriesClient  # noqa: E402
            self._queries = AsyncQueriesClient(client_wrapper=self._client_wrapper)
        return self._queries
    
    @property
    def folders(self):
        if self._folders is None:
            from .folders.client import AsyncFoldersClient  # noqa: E402
            self._folders = AsyncFoldersClient(client_wrapper=self._client_wrapper)
        return self._folders
    
    @property
    def applications(self):
        if self._applications is None:
            from .applications.client import AsyncApplicationsClient  # noqa: E402
            self._applications = AsyncApplicationsClient(client_wrapper=self._client_wrapper)
        return self._applications
    
    @property
    def workflows(self):
        if self._workflows is None:
            from .workflows.client import AsyncWorkflowsClient  # noqa: E402
            self._workflows = AsyncWorkflowsClient(client_wrapper=self._client_wrapper)
        return self._workflows
    
    @property
    def evaluators(self):
        if self._evaluators is None:
            from .evaluators.client import AsyncEvaluatorsClient  # noqa: E402
            self._evaluators = AsyncEvaluatorsClient(client_wrapper=self._client_wrapper)
        return self._evaluators
    
    @property
    def environments(self):
        if self._environments is None:
            from .environments.client import AsyncEnvironmentsClient  # noqa: E402
            self._environments = AsyncEnvironmentsClient(client_wrapper=self._client_wrapper)
        return self._environments
    
    @property
    def deprecated(self):
        if self._deprecated is None:
            from .deprecated.client import AsyncDeprecatedClient  # noqa: E402
            self._deprecated = AsyncDeprecatedClient(client_wrapper=self._client_wrapper)
        return self._deprecated
    
    @property
    def tools(self):
        if self._tools is None:
            from .tools.client import AsyncToolsClient  # noqa: E402
            self._tools = AsyncToolsClient(client_wrapper=self._client_wrapper)
        return self._tools
    
    @property
    def evaluations(self):
        if self._evaluations is None:
            from .evaluations.client import AsyncEvaluationsClient  # noqa: E402
            self._evaluations = AsyncEvaluationsClient(client_wrapper=self._client_wrapper)
        return self._evaluations
    
    @property
    def status(self):
        if self._status is None:
            from .status.client import AsyncStatusClient  # noqa: E402
            self._status = AsyncStatusClient(client_wrapper=self._client_wrapper)
        return self._status
    
    @property
    def projects(self):
        if self._projects is None:
            from .projects.client import AsyncProjectsClient  # noqa: E402
            self._projects = AsyncProjectsClient(client_wrapper=self._client_wrapper)
        return self._projects
    
    @property
    def users(self):
        if self._users is None:
            from .users.client import AsyncUsersClient  # noqa: E402
            self._users = AsyncUsersClient(client_wrapper=self._client_wrapper)
        return self._users
    
    @property
    def keys(self):
        if self._keys is None:
            from .keys.client import AsyncKeysClient  # noqa: E402
            self._keys = AsyncKeysClient(client_wrapper=self._client_wrapper)
        return self._keys
def _get_base_url(*, base_url: typing.Optional[str] = None, environment: AgentaApiEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
